export const ACTION_TYPE = {
  // Trucks
  ADD_TRUCK: 'ADD_TRUCK',
  EDIT_TRUCK: 'EDIT_TRUCK',
  REMOVE_TRUCK: 'REMOVE_TRUCK',
  UPDATE_LOGIN_STATE: 'UPDATE_LOGIN_STATE',
  UPDATE_SEARCHING_STATE: 'UPDATE_SEARCHING_STATE',
  UPDATE_LOGS: 'UPDATE_LOGS',
};

export const ACTION_TYPE_STORAGE_KEY_MAP = {
  // Trucks
  ADD_TRUCK: 'trucks',
  EDIT_TRUCK: 'trucks',
  REMOVE_TRUCK: 'trucks',
  UPDATE_LOGIN_STATE: 'isLoggedIn',
  UPDATE_SEARCHING_STATE: 'isSearching',
  UPDATE_LOGS: 'logs',
};
